CREATE INDEX `idx_acct_user` ON `account` (`userId`);--> statement-breakpoint
CREATE INDEX `idx_admin_branch_active` ON `admin_users` (`branchId`,`isActive`);--> statement-breakpoint
CREATE INDEX `idx_admin_role` ON `admin_users` (`roleId`);--> statement-breakpoint
CREATE INDEX `idx_appt_branch_start` ON `appointments` (`branchId`,`startAt`);--> statement-breakpoint
CREATE INDEX `idx_appt_dentist_start` ON `appointments` (`dentistId`,`startAt`);--> statement-breakpoint
CREATE INDEX `idx_appt_chair_start` ON `appointments` (`chairId`,`startAt`);--> statement-breakpoint
CREATE INDEX `idx_appt_patient_start` ON `appointments` (`patientId`,`startAt`);--> statement-breakpoint
CREATE INDEX `idx_appt_status_start` ON `appointments` (`status`,`startAt`);--> statement-breakpoint
CREATE INDEX `idx_appt_plan_item` ON `appointments` (`treatmentPlanItemId`);--> statement-breakpoint
CREATE INDEX `idx_appt_recall` ON `appointments` (`recallId`);--> statement-breakpoint
CREATE INDEX `idx_audit_patient_created` ON `audit_logs` (`patientId`,`createdAt`);--> statement-breakpoint
CREATE INDEX `idx_audit_entity` ON `audit_logs` (`entityType`,`entityId`);--> statement-breakpoint
CREATE INDEX `idx_audit_actor_created` ON `audit_logs` (`actorId`,`createdAt`);--> statement-breakpoint
CREATE INDEX `idx_chair_branch_active` ON `chairs` (`branchId`,`isActive`);--> statement-breakpoint
CREATE INDEX `idx_comm_reference` ON `communication_logs` (`referenceType`,`referenceId`);--> statement-breakpoint
CREATE INDEX `idx_comm_patient_created` ON `communication_logs` (`patientId`,`createdAt`);--> statement-breakpoint
CREATE INDEX `idx_comm_lead_created` ON `communication_logs` (`leadId`,`createdAt`);--> statement-breakpoint
CREATE INDEX `idx_ii_invoice` ON `invoice_items` (`invoiceId`);--> statement-breakpoint
CREATE INDEX `idx_ii_procedure` ON `invoice_items` (`procedureId`);--> statement-breakpoint
CREATE INDEX `idx_ii_visit_proc` ON `invoice_items` (`visitProcedureId`);--> statement-breakpoint
CREATE INDEX `idx_ii_plan_item` ON `invoice_items` (`treatmentPlanItemId`);--> statement-breakpoint
CREATE INDEX `idx_inv_branch_issue` ON `invoices` (`branchId`,`issueDate`);--> statement-breakpoint
CREATE INDEX `idx_inv_patient_status` ON `invoices` (`patientId`,`status`);--> statement-breakpoint
CREATE INDEX `idx_inv_visit` ON `invoices` (`visitId`);--> statement-breakpoint
CREATE INDEX `idx_inv_plan` ON `invoices` (`treatmentPlanId`);--> statement-breakpoint
CREATE INDEX `idx_la_lead_created` ON `lead_activities` (`leadId`,`createdAt`);--> statement-breakpoint
CREATE INDEX `idx_lead_branch_status` ON `leads` (`branchId`,`status`);--> statement-breakpoint
CREATE INDEX `idx_lead_assignee_followup` ON `leads` (`assignedTo`,`nextFollowUpAt`);--> statement-breakpoint
CREATE INDEX `idx_lead_source_created` ON `leads` (`source`,`createdAt`);--> statement-breakpoint
CREATE INDEX `idx_lead_converted_patient` ON `leads` (`convertedPatientId`);--> statement-breakpoint
CREATE INDEX `idx_login_email_created` ON `login_attempts` (`email`,`createdAt`);--> statement-breakpoint
CREATE INDEX `idx_login_ip_created` ON `login_attempts` (`ipAddress`,`createdAt`);--> statement-breakpoint
CREATE INDEX `idx_notif_user_read` ON `notifications` (`userId`,`isRead`,`createdAt`);--> statement-breakpoint
CREATE INDEX `idx_pc_patient_status` ON `patient_conditions` (`patientId`,`status`);--> statement-breakpoint
CREATE INDEX `idx_pf_patient_created` ON `patient_files` (`patientId`,`createdAt`);--> statement-breakpoint
CREATE INDEX `idx_pf_visit` ON `patient_files` (`visitId`);--> statement-breakpoint
CREATE INDEX `idx_pat_branch_status` ON `patients` (`branchId`,`status`);--> statement-breakpoint
CREATE INDEX `idx_pat_phone` ON `patients` (`phone`);--> statement-breakpoint
CREATE INDEX `idx_pat_portal_user` ON `patients` (`portalUserId`);--> statement-breakpoint
CREATE INDEX `idx_pat_lead` ON `patients` (`leadId`);--> statement-breakpoint
CREATE INDEX `idx_pay_invoice` ON `payments` (`invoiceId`);--> statement-breakpoint
CREATE INDEX `idx_pay_patient_date` ON `payments` (`patientId`,`paymentDate`);--> statement-breakpoint
CREATE INDEX `idx_pay_branch_date` ON `payments` (`branchId`,`paymentDate`);--> statement-breakpoint
CREATE INDEX `idx_rxi_prescription` ON `prescription_items` (`prescriptionId`);--> statement-breakpoint
CREATE INDEX `idx_rx_visit` ON `prescriptions` (`visitId`);--> statement-breakpoint
CREATE INDEX `idx_rx_patient` ON `prescriptions` (`patientId`);--> statement-breakpoint
CREATE INDEX `idx_proc_category_active` ON `procedures` (`category`,`isActive`);--> statement-breakpoint
CREATE INDEX `idx_recall_branch_status_due` ON `recalls` (`branchId`,`status`,`dueDate`);--> statement-breakpoint
CREATE INDEX `idx_recall_patient` ON `recalls` (`patientId`);--> statement-breakpoint
CREATE INDEX `idx_recall_appt` ON `recalls` (`appointmentId`);--> statement-breakpoint
CREATE INDEX `idx_sess_user` ON `sessions` (`userId`);--> statement-breakpoint
CREATE INDEX `idx_sched_branch_day` ON `staff_schedules` (`branchId`,`dayOfWeek`,`isActive`);--> statement-breakpoint
CREATE INDEX `idx_sched_staff` ON `staff_schedules` (`staffId`);--> statement-breakpoint
CREATE INDEX `idx_timeoff_staff_range` ON `staff_time_off` (`staffId`,`startDate`,`endDate`);--> statement-breakpoint
CREATE INDEX `idx_tcm_task_created` ON `task_comments` (`taskId`,`createdAt`);--> statement-breakpoint
CREATE INDEX `idx_task_assignee_status` ON `tasks` (`assignedTo`,`status`,`dueDate`);--> statement-breakpoint
CREATE INDEX `idx_task_patient` ON `tasks` (`patientId`);--> statement-breakpoint
CREATE INDEX `idx_task_lead` ON `tasks` (`leadId`);--> statement-breakpoint
CREATE INDEX `idx_task_branch_status` ON `tasks` (`branchId`,`status`);--> statement-breakpoint
CREATE INDEX `idx_tc_patient_status` ON `tooth_conditions` (`patientId`,`status`);--> statement-breakpoint
CREATE INDEX `idx_tc_visit` ON `tooth_conditions` (`visitId`);--> statement-breakpoint
CREATE INDEX `idx_tc_plan_item` ON `tooth_conditions` (`treatmentPlanItemId`);--> statement-breakpoint
CREATE INDEX `idx_tpi_plan` ON `treatment_plan_items` (`treatmentPlanId`);--> statement-breakpoint
CREATE INDEX `idx_tpi_procedure` ON `treatment_plan_items` (`procedureId`);--> statement-breakpoint
CREATE INDEX `idx_tpi_appt` ON `treatment_plan_items` (`appointmentId`);--> statement-breakpoint
CREATE INDEX `idx_tpi_visit_proc` ON `treatment_plan_items` (`visitProcedureId`);--> statement-breakpoint
CREATE INDEX `idx_tpi_tooth` ON `treatment_plan_items` (`toothConditionId`);--> statement-breakpoint
CREATE INDEX `idx_tp_patient_status` ON `treatment_plans` (`patientId`,`status`);--> statement-breakpoint
CREATE INDEX `idx_tp_branch_proposed` ON `treatment_plans` (`branchId`,`proposedAt`);--> statement-breakpoint
CREATE INDEX `idx_tp_dentist` ON `treatment_plans` (`dentistId`);--> statement-breakpoint
CREATE INDEX `idx_vd_visit` ON `visit_diagnoses` (`visitId`);--> statement-breakpoint
CREATE INDEX `idx_vd_patient` ON `visit_diagnoses` (`patientId`);--> statement-breakpoint
CREATE INDEX `idx_vp_visit` ON `visit_procedures` (`visitId`);--> statement-breakpoint
CREATE INDEX `idx_vp_patient` ON `visit_procedures` (`patientId`);--> statement-breakpoint
CREATE INDEX `idx_vp_performed_by` ON `visit_procedures` (`performedBy`);--> statement-breakpoint
CREATE INDEX `idx_vp_plan_item` ON `visit_procedures` (`treatmentPlanItemId`);--> statement-breakpoint
CREATE INDEX `idx_vp_procedure` ON `visit_procedures` (`procedureId`);--> statement-breakpoint
CREATE INDEX `idx_visit_patient_date` ON `visits` (`patientId`,`visitDate`);--> statement-breakpoint
CREATE INDEX `idx_visit_branch_date` ON `visits` (`branchId`,`visitDate`);--> statement-breakpoint
CREATE INDEX `idx_visit_appt` ON `visits` (`appointmentId`);